version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fx_deals
      MYSQL_USER: abdallah
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fx_deals?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: abdallah
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
